import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { ReduxProvider } from "@/context/ReduxProvider";
import { AuthProvider } from "@/context/AuthContext";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // nanti dipakai di Tailwind
  display: "swap",
});

export const metadata: Metadata = {
  title: "Student Walker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <AuthProvider>
          <ReduxProvider>
            <div className="flex justify-center">
              <div className="max-w-112 min-w-82 w-[100%]">{children}</div>
            </div>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
